databases:
  - name: jbtodo
    databaseName: jbtodo
    user: jbtodo

services:
  - type: web
    name: jbtodo
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jbtodo
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false